zsh: so many changes
- fully modularised zsh config
    - more in line with how i had fish set up, which i liked
- removed most comments, don't need them
- `.zshenv` outside of `.config` just sets `ZDOTDIR`
    - inside it sets env vars
- emptied `.zprofile'
- added catppuccin colors to p10k
    - including `my_git_formatter` override
- added a second single line config for p10k if i want to use
- added `catppuccin.zsh` that sets `z-sy-h` colors
- updated aliases
- updated zsh options
    - 5x HISTSIZE
    - got rid of redundant history options
    - _cursor_block to make sure it's always block cursor
- completion
    - added `zstyle menu select`
        - better completion nav
    - `uv` shell completion
        - added in but commented out for now
    - source `sk` completions
        - not sure if needed
- replaced `fzf` w/ `skim`
- added ssh agent setup
- better plugin sourcing
    - `z-sy-h` is now sourced as the last thing in the config
- updated scripts
    - `cxx`
        - quick one file cpp compile and run
    - `lc[s/d]`
        - `lc`
            - find and run latest edited leetcode `sol.cpp`
        - `lcd`
            - find and run latest edited leetcode `sol.cpp` w/ sanitisers
        - `lcs`
            - `ls` but for leetcode solutions
    - `ogo`
        - obsidian go, moves uncategorised to proper tagged folders
    - `onew`
        - obsidian new, new note in inbox
    - `updatenvim`
        - now builds from source
        - may change to `zig build` when mature
- added functions
    - uvsh now lives here and works a bit better
        - no redundant windows check
        - now toggles venv when ran again
- bumped p10k version

diff --git a/zsh/.config/zsh/scripts/onew b/zsh/.config/zsh/scripts/onew
--- a/zsh/.config/zsh/scripts/onew
+++ b/zsh/.config/zsh/scripts/onew
@@ -1,26 +1,21 @@
 #!/bin/zsh
 
-# check if file name was provided
 if [ -z "$1" ]; then
-  echo "Error: A file name must be set"
-  exit 1
+    echo "Error: A file name must be set"
+    exit 1
 fi
 
-# prepare the file name w/ date suffix and title
 title="$1"
-file_name=$(echo "$title" | sed 's/[ \/]/-/g') # better title sanitisation
+file_name=$(echo "$title" | sed 's/[ \/]/-/g')
 id=${file_name}_$(date "+%Y-%m-%d")
 formatted_file_name=${id}.md
-# paths for vault, template, and destination file
+
 vault_dir="/home/metin/Documents/Obsidian/Main"
 template_file="$vault_dir/templates/note.md"
 destination="$vault_dir/inbox/${formatted_file_name}"
 
-# date formatted
 date_str=$(date "+%Y-%m-%d")
 
-# replace placeholders in template file w/ actual ttle and date
-# using a different delim '|' to avoid issues w/ any '/' in title
 sed -e "s|{{title}}|$title|g" -e "s|{{date}}|$date_str|g" -e "s|{{id}}|$id|g" "$template_file" > "$destination"
 
 nvim "$destination"
